language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '4.2'
  - '5.1'
  - '6.0'
cache:
  directories:
    - node_modules
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower polymer-cli
  - bower i
script:
  - polymer lint --no-recursion
  - polymer test --expanded
  - polymer build
notifications:
  slack: fnndsc:WtDpBdT7VxV8YVD4K0NPHnW1
